clear;
# SEE MORE EXAMPLES WITH: get-help convertto-html -examples
# -- Example 9: Create a webpage displaying services begin with A --

$htmlParams = @{
    Title = "Windows Services: Server01"
    Body = Get-Date
    PreContent = "<P>Generated by Corporate IT</P>"
    PostContent = "For details, contact Corporate IT."
}

Get-Service A* |
    ConvertTo-Html @htmlParams |
        Out-File Service.htm
Invoke-Item Service.htm

sleep 1;
